# Basic Operations and HADAMARD PRODUCT

In [11]:
import numpy as np
import torch
import tensorflow as tf

X = np.array([[11,12],[21,22],[31,32]])
X_pytorch = torch.tensor([[11,12],[21,22],[31,32]])
X_tensorflow = tf.constant([[11,12],[21,22],[31,32]])

# Basic Arithmetic

Applying basic arithmetic (+,-,*,/) with scalar applies operation to all elemens and the shape is preserved.


In [12]:
X

array([[11, 12],
       [21, 22],
       [31, 32]])

In [13]:
# Multiplication with scalar value
# Each element in X is multiplied by 2.

X *2

array([[22, 24],
       [42, 44],
       [62, 64]])

In [14]:
# Addition with Scalar
# Each element in X is added by 3.

X + 3

array([[14, 15],
       [24, 25],
       [34, 35]])

In [15]:
# We can apply multiplication and addition.

X * 2 + 3

array([[25, 27],
       [45, 47],
       [65, 67]])

In Pytorch, we can perform the same operation. 

We use the tensor object, as opposed to the numpy object. The result is the same as the numpy results.

In [10]:
X_pytorch

tensor([[11, 12],
        [21, 22],
        [31, 32]])

Multiplication and addition with scalar value

In [16]:
# Multiplication with scalar value

X_pytorch * 2

tensor([[22, 24],
        [42, 44],
        [62, 64]])

For Pytorch we can also use torch.mul(). 

The result is the same as the previous result.

In [23]:
torch.mul(X_pytorch,2)

tensor([[22, 24],
        [42, 44],
        [62, 64]])

In [17]:
# Addition with scalar value

X_pytorch + 3

tensor([[14, 15],
        [24, 25],
        [34, 35]])

For Pytorch we can also use torch.add().

The result is the same as the previous result.

In [24]:
torch.add(X_pytorch,3)

tensor([[14, 15],
        [24, 25],
        [34, 35]])

In [18]:
# We can apply multiplication and addition.

X_pytorch * 2 + 3

tensor([[25, 27],
        [45, 47],
        [65, 67]])

In [26]:
# We can use torch.mult() to multiply each element by 2 and then use torch.add() to add 3.

# We will get the same result.

torch.add(torch.mul(X_pytorch,2),3)


tensor([[25, 27],
        [45, 47],
        [65, 67]])

In TensorFlow, we can perform the same operation.

We use the tensor object, as opposed to the numpy object. The result is the same as the numpy results.

In [19]:
X_tensorflow

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [21, 22],
       [31, 32]])>

In [20]:
# Multiplication with scalar value.

X_tensorflow * 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 24],
       [42, 44],
       [62, 64]])>

In [27]:
# We can use tf.multiply() to multiply each element by 2.

# We will get the same result.

tf.multiply(X_tensorflow,2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 24],
       [42, 44],
       [62, 64]])>

In [21]:
# Addition with scalar value.

X_tensorflow + 3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 15],
       [24, 25],
       [34, 35]])>

In [28]:
# We can use tf.add() to add 3 to each element.

# We will get the same result.

tf.add(X_tensorflow,3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 15],
       [24, 25],
       [34, 35]])>

In [22]:
# We can apply multiplication and addition.

X_tensorflow * 2 + 3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 27],
       [45, 47],
       [65, 67]])>

In [29]:
# We can use tf.multiply() to multiply each element by 2 and then use tf.add() to add 3.

# We will get the same result.

tf.add(tf.multiply(X_tensorflow,2),3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 27],
       [45, 47],
       [65, 67]])>

# Hadamard Product (Element wise product)

The hadamard product is the element wise product of two tensors.

We can apply the hadamard product between two tensors of the same shape.

In other words, if two tensors have the same size, operations are often applied element-wise.

The hadamard product is the default multiplication for torch tensors and numpy arrays.

This is not matrix multiplication, it is element wise multiplication.



In [31]:
# Let's define A

A = X + 10
A

array([[21, 22],
       [31, 32],
       [41, 42]])

In [32]:
A + X

array([[32, 34],
       [52, 54],
       [72, 74]])

In [33]:
A * X

array([[ 231,  264],
       [ 651,  704],
       [1271, 1344]])

For PyTorch

In [34]:
A_pytorch = X_pytorch + 10
A_pytorch

tensor([[21, 22],
        [31, 32],
        [41, 42]])

In [35]:
A_pytorch + X_pytorch

tensor([[32, 34],
        [52, 54],
        [72, 74]])

In [36]:
A_pytorch * X_pytorch

tensor([[ 231,  264],
        [ 651,  704],
        [1271, 1344]])

For TensorFlow


In [38]:
A_tensorflow = X_tensorflow + 10
A_tensorflow

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21, 22],
       [31, 32],
       [41, 42]])>

In [39]:
A_tensorflow + X_tensorflow

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[32, 34],
       [52, 54],
       [72, 74]])>

In [40]:
A_tensorflow * X_tensorflow

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 231,  264],
       [ 651,  704],
       [1271, 1344]])>

We can apply the hadamard product between two tensors of the same shape.

In other words, if two tensors have the same size, operations are often applied element-wise.