# TENSOR REDUCTION

Calculating the sum across all elements in a tensor is a common operation. This reduces the tensor to a scalar value.

For vector x of length n, the sum is:

$$\sum_{i=1}^{n} x_i$$

For matrix X with dimensions m x n, the sum is:

$$\sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij}$$


In [1]:
import numpy as np
import torch
import tensorflow as tf

X = np.array([[11,12],[21,22],[31,32]])
X_pytorch = torch.tensor([[11,12],[21,22],[31,32]])
X_tensorflow = tf.constant([[11,12],[21,22],[31,32]])

In [2]:
X

array([[11, 12],
       [21, 22],
       [31, 32]])

In [3]:
X.sum()

129

In [6]:
torch.sum(X_pytorch)

tensor(129)

In [7]:
tf.reduce_sum(X_tensorflow)

<tf.Tensor: shape=(), dtype=int32, numpy=129>

Summation can also be done along specific axis.

We can sum all rows (axis=0) or all columns (axis=1).

In [11]:
# Sum Numpy

X

array([[11, 12],
       [21, 22],
       [31, 32]])

In [8]:
X.sum(axis=0)

array([63, 66])

In [9]:
X.sum(axis=1)

array([23, 43, 63])

In [12]:
# Sum Pytorch

X_pytorch

tensor([[11, 12],
        [21, 22],
        [31, 32]])

In [13]:
torch.sum(X_pytorch, dim=0)

tensor([63, 66])

In [14]:
torch.sum(X_pytorch, dim=1)

tensor([23, 43, 63])

In [15]:
# Sum Tensorflow

X_tensorflow

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [21, 22],
       [31, 32]])>

In [16]:
tf.reduce_sum(X_tensorflow, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([63, 66])>

In [17]:
tf.reduce_sum(X_tensorflow, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([23, 43, 63])>

Many other operations can be applied with reduction, such as mean, product, minimum, maximum, standard deviation, and more.

They are fairly straight forward and used less often than the sum operation.

