# DOT PRODUCT

Dot product can only be carried out on vector tensors.

Calculating the dot product of two vectors is one of the most common tensor operation in ML.

If we have two vectors $\mathbf{x}$ and $\mathbf{y}$, with same length n, we can calcualte the dot product between them.

We calculate the products in an element-wise fashion and then sum reductively across the products to a scalar value.

In other words, the dot product is a sum of the products of the corresponding elements of each vector.

$$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^{n} x_i y_i$$

The dot product is ubiquitous in deep learning, it is performed at every artificial neuron in a neural network, which may be made up pf millions of neurons.

In [15]:
import numpy as np
import torch
import tensorflow as tf

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
y_torch = torch.tensor([4, 5, 6])
y_tf = tf.constant([4, 5, 6])

In [10]:
x

array([1, 2, 3])

In [11]:
y

array([4, 5, 6])

In [12]:
dotmanuel_x = 1*4 + 2*5 + 3*6
dotmanuel_x

32

In [14]:
dotnp_x = np.dot(x, y)
dotnp_x

32

In [17]:
dottorch_x = torch.dot(torch.tensor(x), torch.tensor(y))
dottorch_x

tensor(32, dtype=torch.int32)

In [19]:
dottf_x = tf.tensordot(tf.constant(x), tf.constant(y), axes=1)
dottf_x

<tf.Tensor: shape=(), dtype=int32, numpy=32>