In [4]:
import numpy as np
import pandas as pd
import torch
import tensorflow as tf

# EXERCISES

What is the transpose of y?

In [5]:
y = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [6]:
y_ptorch= torch.tensor([[42, 4, 7, 99], [-99, -3, 17, 22]])
y_ptorch

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [7]:
y_tf= tf.constant([[42, 4, 7, 99], [-99, -3, 17, 22]])
y_tf

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])>

In [8]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [9]:
y_ptorch.T

tensor([[ 42, -99],
        [  4,  -3],
        [  7,  17],
        [ 99,  22]])

In [10]:
tf.transpose(y_tf)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])>

# What is the Hadamard product of below matrices?



In [11]:
a = np.array([[25,10], [-2, 1]])
b = np.array([[-1, 7], [10, 8]])

a * b

array([[-25,  70],
       [-20,   8]])

In [12]:
a_ptorch = torch.tensor([[25,10], [-2, 1]])
b_ptorch = torch.tensor([[-1, 7], [10, 8]])

a_ptorch * b_ptorch

tensor([[-25,  70],
        [-20,   8]])

In [13]:
a_tf = tf.constant([[25,10], [-2, 1]])
b_tf = tf.constant([[-1, 7], [10, 8]])

tf.multiply(a_tf, b_tf)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-25,  70],
       [-20,   8]])>

# What is the dot product of below matrices?

In [24]:
w = np.array([-1,2, -2])
x = np.array([5, 10 , 0]) 

# w*x = w_1*x_1 + w_2*x_2 + w_3*x_3

-1 * 5 + 2 * 10 + -2 * 0

15

In [25]:
w.dot(x)

15

In [26]:
w_ptorch = torch.tensor([-1,2, -2])
x_ptorch = torch.tensor([5, 10 , 0])

w_ptorch.dot(x_ptorch)

tensor(15)

In [18]:
torch.sum(torch.multiply(w_ptorch, x_ptorch))

tensor(15)

In [27]:
w_tf = tf.constant([-1,2, -2])
x_tf = tf.constant([5, 10 , 0])

tf.tensordot(w_tf, x_tf, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [21]:
tf.reduce_sum(tf.multiply(w_tf, x_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=15>