# TENSOR TRANSPOSITION

The easiest tensors to transpose is a zero dimentional tensor, which is a scalar. A scalar is a tensor with no axes. The transpose of a scalar is itself.

Transpose of scalar is itself: $x^T = x$

Transpose of a vector converts a row vector to a column vector and vice versa.

Matrix transpose is a generalization of scalar and vector transposition.

 In matrix tranpose, the rows of the input matrix becomes the columns of the output matrix and vice versa.  
 
  - We flip of axes over main diagonal.
 
$$ X_{ij}^T = X_{ji}$$

* Matrix of 3 rows and 2 columns transposed to a matrix of 2 rows and 3 columns.


$$ 

\begin{bmatrix}
    x_1,_1 & x_1,_2 \\
    x_2,_1 & x_2,_2 \\
    x_3,_1 & x_3,_2 \\
\end{bmatrix}^T =

\begin{bmatrix}
    x_1,_1 & x_2,_1 & x_3,_1 \\
    x_1,_2 & x_2,_2 & x_3,_2 \\
\end{bmatrix}
$$

$$ 

\begin{bmatrix}
    11 & 12 \\
    21 & 22 \\
    31 & 32 \\
\end{bmatrix}^T =

\begin{bmatrix}
    11 & 21 & 31 \\
    12 & 22 & 32 \\
    
\end{bmatrix}
$$



In [6]:
import numpy as np
import torch
import tensorflow as tf

X= np.array([[11,12],[21,22],[31,32]])
X

array([[11, 12],
       [21, 22],
       [31, 32]])

In [8]:
# numpy transpose

X_t = X.T
X_t

array([[11, 21, 31],
       [12, 22, 32]])

In [10]:
# torch transpose

X_torchtranspose = X.T
X_torchtranspose

array([[11, 21, 31],
       [12, 22, 32]])

In [11]:
X_tensorTranspose = tf.transpose(X)
X_tensorTranspose

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 21, 31],
       [12, 22, 32]])>