# EXERCISE

1. Create a vector and take its tranpose.



In [6]:
import numpy as np

x_np = np.array([[25, 2, -3, -23]])
x_np

array([[ 25,   2,  -3, -23]])

In [7]:
# transpose

x_np.T

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [8]:
import torch

x = torch.tensor([[25, 2, -3, -23]])
x  

tensor([[ 25,   2,  -3, -23]])

In [9]:
# transpose

x.T

tensor([[ 25],
        [  2],
        [ -3],
        [-23]])

In [10]:
import tensorflow as tf

x_tf = tf.Variable([[25, 2, -3, -23]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[ 25,   2,  -3, -23]])>

In [13]:
# transpose
x_tft = tf.transpose(x_tf)
x_tft

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 25],
       [  2],
       [ -3],
       [-23]])>

# EXERCISE

2-) What are the dimensions of the following tensor?



In [14]:
import numpy as np

y_np = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
y_np

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [15]:
y_np.shape

(2, 4)

In [21]:
import torch

y = torch.tensor([[42, 4, 7, 99], [-99, -3, 17, 22]])
y


tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [22]:
y.shape

torch.Size([2, 4])

In [23]:
import tensorflow as tf

y_tf = tf.Variable([[42, 4, 7, 99], [-99, -3, 17, 22]])
y_tf

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])>

In [24]:
y_tf.shape

TensorShape([2, 4])

# EXERCISE

3- What is the position of the element in y matrix with the value 17? 

In [25]:
import numpy as np

y_np = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])

y_np

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [26]:
y_np[1,2]

17

In [27]:
import torch

y = torch.tensor([[42, 4, 7, 99], [-99, -3, 17, 22]])
y

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [28]:
y[1,2]

tensor(17)

In [30]:
import tensorflow as tf

y_tf = tf.Variable([[42, 4, 7, 99], [-99, -3, 17, 22]])
y_tf

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])>

In [31]:
y_tf[1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=17>