# VECTORS

Vectors are one-dimensional array of numbers.

Vectors are arranged in an order, so all the elements in the vector are in a specific position.

Vector elements can be accessed by its index.

Vector elements are scalars.

Vectors represent a particular point in space.

Vector of length two represents a point in a 2D matrix.

Vector of length three represents a point in a 3D cube.

Vector of length n represents a point in an n-dimensional space.



## VECTOR TRANPOSE

Vector transpose is a vector with the same elements but arranged in a different order.

Vector transpose is denoted by a superscript T.

Transpose makes a row vector into a column vector and vice versa.

All the elements in a vector remain the same after transpose.

Original vector:

$$
\begin{bmatrix}
    x_1 & x_2 & x_3
\end{bmatrix}^T 

= 

\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
$$

First one is Row Vector: Shape is (1, 3)
Second one is Column Vector: Shape is (3, 1)

## VECTORS (RANK 1 TENSORS) in NumPy

Vectors are rank 1 tensors.

In [2]:
import numpy as np

x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]

25

In [7]:
type(x[0])

numpy.int32

## Vector Transposing



In [8]:
# Transposing a regular 1-D array has no effect...

# The reason for this is because a regular 1-D array where we specify just with one set of brackets is neither a row nor a column vector.

# There is no second dimension to transpose into.

x_t = x.T
x_t

array([25,  2,  5])

In [9]:
x_t.shape

(3,)

In [10]:
#... but it does when we use nested "matrix-style" brackets. By adding extra brackets, we are creating a nested array, which is a 2-D array.

# The reason for this is because a nested array is a 2-D array, and so it has two dimensions to transpose between.

y= np.array([[25, 2, 5]])
y


array([[25,  2,  5]])

In [11]:
y.shape

(1, 3)

In [12]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [13]:
y_t.shape

(3, 1)

In [15]:
# We can also transpose back to the original vector.

y_t_t = y_t.T
y_t_t

array([[25,  2,  5]])

# Zero Vectors


In [16]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in Torch and TensorFlow

In [17]:
import torch
import tensorflow as tf


In [18]:
x_torch = torch.tensor([25, 2, 5])
x_torch

tensor([25,  2,  5])

In [19]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>