# MATRIX TENSORS

A matrix is a two dimensional array of numbers. 

$$
\begin{bmatrix}
x_{11} & x_{12} \\
x_{21} & x_{22} \\
x_{31} & x_{32} \\
\end{bmatrix}
$$



# Matrices (Rank 2 Tensors) in Numpy

In [16]:
import numpy as np
# We use numpy arrays (np.array) with nested brackets to represent matrices.

X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [17]:
X.shape

(3, 2)

In [18]:
X.size

6

In [19]:
# Select left column of matrix X

X[:,0]

array([25,  5,  3])

In [20]:
# Select middle row of matrix X

X[1,:]

array([ 5, 26])

# Matrices in PyTorch

In [21]:
import torch

X_pytorch = torch.tensor([[25,2],[5,26],[3,7]])
X_pytorch

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [22]:
X_pytorch.shape

torch.Size([3, 2])

In [23]:
X_pytorch[1,:]

tensor([ 5, 26])

# Matrices in TensorFlow

In [24]:
import tensorflow as tf

In [25]:
X_tf = tf.Variable([[25,2],[5,26],[3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [26]:
tf.rank(X_tf)

# numpy 0 scalar. 
# numpy 1 is vector
# numpy 2 is matrix

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [27]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [28]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>